First we wrote some code to find an exact matching of the classes

In [3]:
import logging

import pandas as pd
logger = logging.getLogger(__name__)

In [27]:
class StringMatcher():    
    def __init__(self) -> None:
        self.df_dbpedia = pd.read_csv("./files/dbpedia_classes.csv")

        
    def match_exact_string(self, string:str) -> str:
        """method that gives us the dbpedia class to a given string
        Args: TODO:update description pls
            string (str): the class we are looking for
        Returns:
            pd.DataFrame: returns a DataFrame with the corresponding classes from dbpedia
        """
        substrings = string.split(",") 

        #we remove the blanks in front of every class
        stripped_substrings = [s.strip() for s in substrings]
        output = ""
        for str in stripped_substrings:
            if self.df_dbpedia['label'].eq(str).any():
                output = str      
            else:
                logger.info("Couldnt find matching string to: {str}")
        return output
    
    def match_lowercase_exact_string(self, string:str) -> str:
        substrings = string.split(",") 

        #we remove the blanks in front of every class
        stripped_substrings = [s.strip() for s in substrings]
        output = ""
        for str in stripped_substrings:
            if self.df_dbpedia['label'].eq(str.lower()).any():
                output = str      
            else:
                logger.info("Couldnt find matching string to: {str}")
        return output

We init our String Matcher, this class matches a String exactly to a dbpedia class and creates a dataframe that shows us the matching

In [21]:
string_matcher = StringMatcher()

#dataframe with all imagenet classes
df_imgnet = pd.read_csv("./files/ImageNet.csv") 

#dataframe where we put in our results
df_exact_matching = pd.DataFrame(columns = ["image_net_class","dbpedia_class"])
list_exact_matching = []
for rowIndex, row in df_imgnet.iterrows():
    new_row = string_matcher.match_exact_string(row[1])
    if new_row:
        logger.info("ImageNet Class: {new_row}, DBpedia Class. {row[1]}")
        df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
        list_exact_matching.append([new_row, row[1]])

#df_exact_matching.head(100)
#print(list_exact_matching)
df = pd.DataFrame (list_exact_matching, columns = ['dbpedia_classes', 'image_net_classes'])
df.head(100)

bird
boxer
painter
monarch
amphibian
lighthouse
castle
mobile phone
church
dike
file
library
monastery
mosque
organ
coach
prison
restaurant
space shuttle
streetcar

C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)

website
valley
volcano
baseball player

C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)
C:\Users\David\AppData\Local\Temp\ipykernel_13192\3616472781.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_exact_matching.append({'image_net_class': new_row, "dbpedia_class": row[1]}, ignore_index=True)

    dbpedia_classes                                  image_net_classes
0              bird                                        crane, bird
1             boxer                                              boxer
2           painter  cougar, puma, catamount, mountain lion, painte...
3           monarch  monarch, monarch butterfly, milkweed butterfly...
4         amphibian                      amphibian, amphibious vehicle
5        lighthouse           beacon, lighthouse, beacon light, pharos
6            castle                                             castle
7      mobile phone  cellular telephone, cellular phone, cellphone,...
8            church                            church, church building
9              dike                                    dam, dike, dyke
10             file                 file, file cabinet, filing cabinet
11          library                                            library
12        monastery                                          monastery
13           mosque                                             mosque
14            organ                                  organ, pipe organ
15            coach                     passenger car, coach, carriage
16           prison                               prison, prison house
17       restaurant     restaurant, eating house, eating place, eatery
18    space shuttle                                      space shuttle
19        streetcar     streetcar, tram, tramcar, trolley, trolley car
20          website             web site, website, internet site, site
21           valley                                       valley, vale
22          volcano                                            volcano
23  baseball player                        ballplayer, baseball player

As we can see in row 3: Monarch is linked to Monarch Butterfly => So we need to think if this could be a problem

As a next step we use another method of our StringMatcher class to find classes that doesnt have an exact matching but still match if we change to class from Image_net to a lowercase string

In [28]:
string_matcher = StringMatcher()

#dataframe with all imagenet classes
df_imgnet = pd.read_csv("./files/ImageNet.csv") 

#dataframe where we put in our results
list_exact_matching = []
for rowIndex, row in df_imgnet.iterrows():
    new_row = string_matcher.match_lowercase_exact_string(row[1])
    if new_row:
        logger.info("ImageNet Class: {new_row}, DBpedia Class. {row[1]}")
        
        list_exact_matching.append([new_row, row[1]])
        
df = pd.DataFrame (list_exact_matching, columns = ['dbpedia_classes', 'image_net_classes'])
df.head(100)

    dbpedia_classes                                  image_net_classes
0              bird                                        crane, bird
1             boxer                                              boxer
2           painter  cougar, puma, catamount, mountain lion, painte...
3           monarch  monarch, monarch butterfly, milkweed butterfly...
4         amphibian                      amphibian, amphibious vehicle
5        lighthouse           beacon, lighthouse, beacon light, pharos
6            castle                                             castle
7      mobile phone  cellular telephone, cellular phone, cellphone,...
8            church                            church, church building
9              dike                                    dam, dike, dyke
10             file                 file, file cabinet, filing cabinet
11          library                                            library
12        monastery                                          monastery
13           mosque                                             mosque
14            organ                                  organ, pipe organ
15            coach                     passenger car, coach, carriage
16           prison                               prison, prison house
17       restaurant     restaurant, eating house, eating place, eatery
18    space shuttle                                      space shuttle
19        streetcar     streetcar, tram, tramcar, trolley, trolley car
20          website             web site, website, internet site, site
21           valley                                       valley, vale
22          volcano                                            volcano
23  baseball player                        ballplayer, baseball player

As we can see we still have 23 classes so nothing changes if we convert all inputs to a lowercase string

Now we save these 23 classes in their own .csv file

In [33]:
df.to_csv('exact_matching.csv', index=False)

Now we drop these 23 classes from our ImageNet.csv for further processing

In [39]:
df_exact = pd.read_csv("./files/exact_matching.csv")
df_exact_image_net = pd.DataFrame(df_exact["image_net_classes"])
df_exact_image_net.head(10000)

#TODO: @Tianran: kannst du ab hier weitermachen

                                    image_net_classes
0                                         crane, bird
1                                               boxer
2   cougar, puma, catamount, mountain lion, painte...
3   monarch, monarch butterfly, milkweed butterfly...
4                       amphibian, amphibious vehicle
5            beacon, lighthouse, beacon light, pharos
6                                              castle
7   cellular telephone, cellular phone, cellphone,...
8                             church, church building
9                                     dam, dike, dyke
10                 file, file cabinet, filing cabinet
11                                            library
12                                          monastery
13                                             mosque
14                                  organ, pipe organ
15                     passenger car, coach, carriage
16                               prison, prison house
17     restaurant, eating house, eating place, eatery
18                                      space shuttle
19     streetcar, tram, tramcar, trolley, trolley car
20             web site, website, internet site, site
21                                       valley, vale
22                                            volcano
23                        ballplayer, baseball player