In [18]:
import pandas as pd
import numpy as np

In [19]:
df_wordNet_imageNet = pd.read_csv("./files/wordnet_to_imagenet.csv",sep=': ',names=["wordNet_class","imageNet_class"],header = None)
df_wordNet_imageNet

C:\Users\David\AppData\Local\Temp\ipykernel_15820\1519717503.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_wordNet_imageNet = pd.read_csv("./files/wordnet_to_imagenet.csv",sep=': ',names=["wordNet_class","imageNet_class"],header = None)

    wordNet_class                                     imageNet_class
0      "n02119789                          kit fox, Vulpes macrotis"
1       n02100735                                     English setter
2       n02096294                                 Australian terrier
3      "n02066245  grey whale, gray whale, devilfish, Eschrichtiu...
4      "n02509815  lesser panda, red panda, panda, bear cat, cat ...
..            ...                                                ...
995     n02086646                                   Blenheim spaniel
996    "n02091244                      Ibizan hound, Ibizan Podenco"
997     n02089973                                   English foxhound
998     n02105251                                             briard
999     n02093754                                     Border terrier

[1000 rows x 2 columns]

In [20]:
df_wikidata_wordNet = pd.read_csv("./files/wikidata_to_wordnet.csv")
df_wikidata_wordNet.rename(columns={"item":"wikidata_class", "itemLabel":"item_label", "uri":"wordNet_class"})

,wikidata_class,item_label,wordNet_class
0,http://www.wikidata.org/entity/Q144,dog,http://wordnet-rdf.princeton.edu/wn30/02084071-n
1,http://www.wikidata.org/entity/Q177,pizza,http://wordnet-rdf.princeton.edu/wn30/07873807-n
2,http://www.wikidata.org/entity/Q5414,Great Dane,http://wordnet-rdf.princeton.edu/wn30/02109047-n
3,http://www.wikidata.org/entity/Q7987,mouse,http://wordnet-rdf.princeton.edu/wn30/03793489-n
4,http://www.wikidata.org/entity/Q11707,restaurant,http://wordnet-rdf.princeton.edu/wn30/04081281-n
...,...,...,...
457,http://www.wikidata.org/entity/Q13389713,snorkel,http://wordnet-rdf.princeton.edu/wn30/04251144-n
458,http://www.wikidata.org/entity/Q6817227,water bottle,http://wordnet-rdf.princeton.edu/wn30/04557648-n
459,http://www.wikidata.org/entity/Q38132106,soup bowl,http://wordnet-rdf.princeton.edu/wn30/04263257-n
460,http://www.wikidata.org/entity/Q47493881,water jug,http://wordnet-rdf.princeton.edu/wn30/04560804-n
461,http://www.wikidata.org/entity/Q33609,polar bear,http://wordnet-rdf.princeton.edu/wn30/02134084-n/

In [21]:
df_dbpedia_wikidata = pd.read_csv("./files/dbpedia_to_wikidata.csv")
df_dbpedia_wikidata= df_dbpedia_wikidata.rename(columns={"DBpediaClass":"dbpedia_class", "itemLabel":"item_label", "WikidataClass":"wikidata_class"})

df_dbpedia_wikidata[:20]

,dbpedia_class,item_label,wikidata_class
0,http://dbpedia.org/ontology/AcademicConference,academic conference,http://www.wikidata.org/entity/Q2020153
1,http://dbpedia.org/ontology/AcademicSubject,academic subject,http://www.wikidata.org/entity/Q11862829
2,http://dbpedia.org/ontology/Activity,activity,http://www.wikidata.org/entity/Q1914636
3,http://dbpedia.org/ontology/Actor,actor,http://www.wikidata.org/entity/Q33999
4,http://dbpedia.org/ontology/AdministrativeRegion,administrative region,http://www.wikidata.org/entity/Q3455524
5,http://dbpedia.org/ontology/AdultActor,adult (pornographic) actor,http://www.wikidata.org/entity/Q488111
6,http://dbpedia.org/ontology/Agent,agent,http://www.wikidata.org/entity/Q24229398
7,http://dbpedia.org/ontology/Aircraft,aircraft,http://www.wikidata.org/entity/Q11436
8,http://dbpedia.org/ontology/Airline,airline,http://www.wikidata.org/entity/Q46970
9,http://dbpedia.org/ontology/Airport,airport,http://www.wikidata.org/entity/Q1248784
10,http://dbpedia.org/ontology/Album,album,http://www.wikidata.org/entity/Q482994
11,http://dbpedia.org/ontology/Algorithm,Algorithm,http://www.wikidata.org/entity/Q8366
12,http://dbpedia.org/ontology/Altitude,altitude,http://www.wikidata.org/entity/Q190200
13,http://dbpedia.org/ontology/Ambassador,ambassador,http://www.wikidata.org/entity/Q121998
14,http://dbpedia.org/ontology/AmericanFootballPl...,american football player,http://www.wikidata.org/entity/Q14128148
15,http://dbpedia.org/ontology/AnatomicalStructure,anatomical structure,http://www.wikidata.org/entity/Q4936952
16,http://dbpedia.org/ontology/Animal,animal,http://www.wikidata.org/entity/Q729
17,http://dbpedia.org/ontology/Anime,Anime,http://www.wikidata.org/entity/Q1107
18,http://dbpedia.org/ontology/Archeologist,archeologist,http://www.wikidata.org/entity/Q3621491
19,http://dbpedia.org/ontology/Archipelago,archipelago,http://www.wikidata.org/entity/Q33837

In [22]:
df_dbpedia_wikidata

,dbpedia_class,item_label,wikidata_class
0,http://dbpedia.org/ontology/AcademicConference,academic conference,http://www.wikidata.org/entity/Q2020153
1,http://dbpedia.org/ontology/AcademicSubject,academic subject,http://www.wikidata.org/entity/Q11862829
2,http://dbpedia.org/ontology/Activity,activity,http://www.wikidata.org/entity/Q1914636
3,http://dbpedia.org/ontology/Actor,actor,http://www.wikidata.org/entity/Q33999
4,http://dbpedia.org/ontology/AdministrativeRegion,administrative region,http://www.wikidata.org/entity/Q3455524
...,...,...,...
650,http://dbpedia.org/ontology/ہینڈ_بال_جماعت,handball team,http://www.wikidata.org/entity/Q10517054
651,http://dbpedia.org/ontology/ہینڈ_بال_کا_کھلاڑی,handball player,http://www.wikidata.org/entity/Q13365117
652,http://dbpedia.org/ontology/یادگار,memorial,http://www.wikidata.org/entity/Q4989906
653,http://dbpedia.org/ontology/یوکاریوٹ۔,eukaryote,http://www.wikidata.org/entity/Q19088
654,http://dbpedia.org/ontology/یہودیوں_کی_عبادت_گاہ,synagogue,http://www.wikidata.org/entity/Q34627

In [45]:
s1 = pd.merge(df_wikidata_wordNet, df_dbpedia_wikidata, how='inner', on=['wikidata_class'])
s1.drop_duplicates("item_label", inplace = True) #we get duplicates because dbpedia_classes from another language are involved
s1

,wikidata_class,itemLabel,uri,dbpedia_class,item_label
0,http://www.wikidata.org/entity/Q11707,restaurant,http://wordnet-rdf.princeton.edu/wn30/04081281-n,http://dbpedia.org/ontology/Restaurant,restaurant
1,http://www.wikidata.org/entity/Q274153,water tower,http://wordnet-rdf.princeton.edu/wn30/04562935-n,http://dbpedia.org/ontology/WaterTower,Water tower
3,http://www.wikidata.org/entity/Q16970,church building,http://wordnet-rdf.princeton.edu/wn30/03028079-n,http://dbpedia.org/ontology/Church,church
5,http://www.wikidata.org/entity/Q23413,castle,http://wordnet-rdf.princeton.edu/wn30/02980441-n,http://dbpedia.org/ontology/Castle,castle
6,http://www.wikidata.org/entity/Q48806,Space Shuttle,http://wordnet-rdf.princeton.edu/wn30/04266014-n,http://dbpedia.org/ontology/SpaceShuttle,space shuttle
8,http://www.wikidata.org/entity/Q41253,movie theater,http://wordnet-rdf.princeton.edu/wn30/03032252-n,http://dbpedia.org/ontology/Cinema,cinema (movie theater)
10,http://www.wikidata.org/entity/Q39816,valley,http://wordnet-rdf.princeton.edu/wn30/09468604-n,http://dbpedia.org/ontology/Valley,valley
12,http://www.wikidata.org/entity/Q40357,prison,http://wordnet-rdf.princeton.edu/wn30/04005630-n,http://dbpedia.org/ontology/Prison,prison
14,http://www.wikidata.org/entity/Q44613,monastery,http://wordnet-rdf.princeton.edu/wn30/03781244-n,http://dbpedia.org/ontology/Monastery,monastery
16,http://www.wikidata.org/entity/Q32815,mosque,http://wordnet-rdf.princeton.edu/wn30/03788195-n,http://dbpedia.org/ontology/Mosque,mosque

In [46]:
#we make some preprocessing to get the uri in the correct format
uri_list = s1["uri"].to_list()

wordnet_list = []
for el in uri_list:
    foo = el.split("/")[4] #we split the string and receive the wordnet_class at foo[4]
    wd_class = foo.split("-")[0]
    wd_class = "n" + wd_class
    wordnet_list.append(wd_class)
wordnet_list

['n04081281',
 'n04562935',
 'n03028079',
 'n02980441',
 'n04266014',
 'n03032252',
 'n09468604',
 'n04005630',
 'n03781244',
 'n03788195']

In [50]:
wordnet_class = pd.DataFrame(wordnet_list, columns=["wordNet_class"])
baseline = pd.merge(wordnet_class, df_wordNet_imageNet, how='inner', on=['wordNet_class'])
baseline

TypeError: Must pass DataFrame or 2-d ndarray with boolean values only